import { redirect } from "next/navigation";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import "@/app/ui/global.css";
import { inter } from "@/app/ui/fonts";
import BreadCrumbs from "@/components/BreadCrumbs";
// import { getMe } from "@/lib/apis/backend/get-me";
// import { ClientRoutes } from "@/app.config";

// TODO:
// - add metadata

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const me = await getMe();

  // if (!me) redirect(ClientRoutes.signin);

  // console.log(me); // SCAFF

  return (
    <html lang="en">
      <body className={`grid min-h-screen grid-rows-12 ${inter.className} antialiased bg-gray-100`}>

        {/* Header */}
        <div className="">
          <NavBar
            CTALabel="Sign Out"
            CTAHref="#"
          />
        </div>

        <div className="p-5 row-span-10">
          <BreadCrumbs />
          <main>
            {children}
          </main>
        </div>

        <Footer />
      </body>
    </html>
  )
}
